---
title: "Penny-Matching"
output: html_document
date: "2026-02-13"
---

```{r}
#install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, tibble, paletteer, ggthemes)
```


```{r}
#the two default players (add 2 more)

#entirely random
RandomAgent_f <- function(rate){
  choice <- rbinom(1,1, rate)
  return (choice)
}

#WSLS (unchanged)
WSLSAgent_f <- function(prevChoice, feedback){
  if (feedback == 1){
    choice = prevChoice
  } else if (feedback ==0){
    choice = (1 - prevChoice)
  }
  return(choice)
}

#WSLS (switch on wins and loses occasionally)
WSLSAgent_f <- function(prevChoice, feedback, switchProblose = 0.3, switchProbwin = 0.1){
  if (feedback == 1){
    if (runif(1) < switchProbwin){
      choice = (1 - prevChoice)
    } else {
      choice = prevChoice
    }
  } else if (feedback == 0){ #
        if (runif(1) < switchProblose){ 
      choice = (prevChoice)
    } else {
      choice = (1 - prevChoice)
    }
  }
  return(choice)
}

```


```{r}
trials <- 120
n_participants <- 100

randomChoice <- (rep(NA,trials))
rate <- 0.5

#random
for (t in seq(trials)){
  randomChoice[t] <- RandomAgent_f(rate)
}

d1 <- tibble(trial = seq(trials), choice = randomChoice)
p1 <- ggplot(d1, aes(trial,choice)) + geom_line() + theme_classic()
#p1
```

```{r}
set.seed(2999)

#WSLS playing against Random
WSLSChoice <- rep(NA, trials)
WSLSChoice[1] <- RandomAgent_f(rate)

for (i in 2:trials){
  if (randomChoice[i-1] == WSLSChoice[i-1]){
    feedback = 1
  } else {feedback = 0}
  WSLSChoice[i] <- WSLSAgent_f(WSLSChoice[i-1], feedback)
}

df_basic <- tibble(
  randomChoice,
  WSLSChoice,
  trials = seq(trials),
  feedback = as.numeric(randomChoice == WSLSChoice))
  
plot1 <- ggplot(df_basic) + 
  theme_classic() + 
  geom_line(color = "red", aes(trials, randomChoice)) + 
  geom_line(color = "blue", aes(trials, WSLSChoice))


ggplot(df_basic) +
  geom_bar(aes(x = trials, y = randomChoice, fill = "randomChoice"), stat = "identity") +
  geom_bar(aes(x = trials, y = -WSLSChoice, fill = "WSLSChoice"), stat = "identity") +
  theme_tufte() + 
  labs(x = "Trials", y = "Win", fill = "Variable", title = "Random Choice vs Normal WSLS") +
  scale_fill_manual(values = c("randomChoice" = "#7df3e1", "WSLSChoice" = "#FFC067")) +
  scale_y_continuous(limits = c(-1, 1), breaks = c(-1, 0, 1), labels = c("1", "0", "1")) +
  theme(
    plot.title = element_text(size = 16),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    panel.grid.major = element_line(color = "gray90", linewidth = 0.5),
    panel.grid.minor = element_blank()
  )

plot1
count(df_basic, randomChoice) #58 wins out of 120
count(df_basic, WSLSChoice) #56 wins out of 120
```

#WSLS (change occasionally)
```{r}
set.seed(3000)

WSLS_switch_Choice <- rep(NA, trials)
WSLS_switch_Choice[1] <- RandomAgent_f(rate)

for (i in 2:trials){
  if (randomChoice[i-1] == WSLS_switch_Choice[i-1]){
    feedback = 1
  } else {
    feedback = 0
  }
  WSLS_switch_Choice[i] <- WSLSAgent_f(WSLS_switch_Choice[i-1], feedback, switchProbwin = 0.1, switchProblose = 0.3 )
}


df_random <- tibble(
  randomChoice,
  WSLS_switch_Choice,
  trials = seq(trials),
  feedback = as.numeric(randomChoice == WSLS_switch_Choice))
  
ggplot(df_random) + 
  theme_classic() + 
  geom_line(color = "red", aes(trials, randomChoice)) + 
  geom_line(color = "blue", aes(trials, WSLS_switch_Choice))

ggplot(df_random) +
  geom_bar(aes(x = trials, y = randomChoice, fill = "randomChoice"), stat = "identity") +
  geom_bar(aes(x = trials, y = -WSLS_switch_Choice, fill = "WSLS_switch_Choice"), stat = "identity") +
  theme_tufte() + 
  labs(x = "Trials", y = "Win", fill = "Variable", title = "Random Choice vs Adjusted Ratios WSLS") +
  scale_fill_manual(values = c("randomChoice" = "#7df3e1", "WSLS_switch_Choice" = "pink")) +
  scale_y_continuous(limits = c(-1, 1), breaks = c(-1, 0, 1), labels = c("1", "0", "1")) +
  theme(
    plot.title = element_text(size = 16),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    panel.grid.major = element_line(color = "gray90", linewidth = 0.5),
    panel.grid.minor = element_blank()
  )

count(df_random, randomChoice) #58 wins out of 120
count(df_random, WSLS_switch_Choice) #63 wins out of 120
```

```{r}
#Against normal WSLS


set.seed(3000)

WSLS_switch_Choice <- rep(NA, trials)
WSLS_switch_Choice[1] <- RandomAgent_f(rate)

for (i in 2:trials){
  if (WSLSChoice[i-1] == WSLS_switch_Choice[i-1]){
    feedback = 1
  } else {
    feedback = 0
  }
  WSLS_switch_Choice[i] <- WSLSAgent_f(WSLS_switch_Choice[i-1], feedback, switchProbwin = 0.1, switchProblose = 0.3 )
}


df <- tibble(
  WSLSChoice,
  WSLS_switch_Choice,
  trials = seq(trials),
  feedback = as.numeric(WSLSChoice == WSLS_switch_Choice))
  


ggplot(df) +
  geom_bar(aes(x = trials, y = WSLSChoice, fill = "WSLSChoice"), stat = "identity") +
  geom_bar(aes(x = trials, y = -WSLS_switch_Choice, fill = "WSLS_switch_Choice"), stat = "identity") +
  theme_tufte() + 
  labs(x = "Trials", y = "Win", fill = "Variable", title = "Normal WSLS vs Adjusted Ratios WSLS") +
  scale_fill_manual(values = c("WSLSChoice" = "#FFC067", "WSLS_switch_Choice" = "pink")) +
  scale_y_continuous(limits = c(-1, 1), breaks = c(-1, 0, 1), labels = c("1", "0", "1")) +
  theme(
    plot.title = element_text(size = 16),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    panel.grid.major = element_line(color = "gray90", linewidth = 0.5),
    panel.grid.minor = element_blank()
  )
  

count(df, WSLSChoice) #64 wins out of 120
count(df, WSLS_switch_Choice) #68 wins out of 120
```

```{r}
StratSwitcherChoice_f <- function(Other_Player, rate) {
  StratSwitcherChoice <- rep(NA, trials)
  StratSwitcherChoice[1] <- RandomAgent_f(rate) #picks random on first trial
  
  ResultMemory <- rep(NA, 5)
  WSLS_strategy <- TRUE
  feedback = NA
  
  StratSwitcherChoice[1] <- RandomAgent_f(rate)
  
  for (i in 2:trials) {
    #Starts off with checking feedback
    if (Other_Player[i - 1] == StratSwitcherChoice[i - 1]) {
      feedback = 1
    } else {
      feedback = 0
    }
    
    #add feedback to memory (5 tiles long)
    index <- ((i - 1) %% 5) + 1 #so its max 5
    ResultMemory[index] <- feedback
    
    #switches choices every 5 trials if the last 5 trials have been bad
    if (i %% 5 == 0 && sum(ResultMemory, na.rm = TRUE) < 3) {
      #cat("Ahhh, I hate failure... switching; WSLS_strategy: ",WSLS_strategy,"trial number:" ,i, "win amount in last 5:", sum(ResultMemory, na.rm = TRUE), "\n")
      if (WSLS_strategy == TRUE) {
        WSLS_strategy = FALSE
      } else {
        WSLS_strategy = TRUE
      }
    }
    
    #either plays WSLS or Random otherwise
    if (WSLS_strategy == TRUE) {
      StratSwitcherChoice[i] <- WSLSAgent_f(StratSwitcherChoice[i - 1], feedback)
    } else {
      StratSwitcherChoice[i] <- RandomAgent_f(rate)
    }
  }
  return (StratSwitcherChoice)
}

StratSwitcherChoice_against_AdjustedRatio <- StratSwitcherChoice_f(Other_Player = WSLS_switch_Choice, rate = 0.5)


#final boss
df1 <- df_f(WSLS_switch_Choice, StratSwitcherChoice_against_Random, trials)
plot_f(df1, WSLS_switch_Choice, StratSwitcherChoice_against_Random, trials )

ggplot(df1) +
  geom_bar(aes(x = trials, y = WSLS_switch_Choice, fill = "WSLS_switch_Choice"), stat = "identity") +
  geom_bar(aes(x = trials, y = -StratSwitcherChoice_against_Random, fill = "StratSwitcherChoice_against_Random"), stat = "identity") +
  theme_tufte() + 
  labs(x = "Trials", y = "Win", fill = "Variable", title = "Adjusted Ratio vs Strategy Switcher") +
  scale_fill_manual(values = c("WSLS_switch_Choice" = "lightpink", "StratSwitcherChoice_against_Random" = "lightgreen")) +
  scale_y_continuous(limits = c(-1, 1), breaks = c(-1, 0, 1), labels = c("1", "0", "1")) +
  theme(
    plot.title = element_text(size = 16),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    panel.grid.major = element_line(color = "gray90", linewidth = 0.5),
    panel.grid.minor = element_blank()
  )

count(df1, player1) #69 wins out of 120, this is stratswitch?
count(df1, player2) #58 wins out of 120, i assume this is wsls
```

