---
title: "Penny-Matching"
output: html_document
date: "2026-02-13"
---

```{r}
#install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, tibble)
set.seed(1234)
```

Code from the Slides!

```{r}
#the two default players (add 2 more)

#entirely random
RandomAgent_f <- function(rate){
  choice <- rbinom(1,1,rate)
  return (choice)
}

#WSLS (unchanged)
WSLSAgent_f <- function(prevChoice, feedback){
  if (feedback == 1){
    choice = prevChoice
  } else if (feedback ==0){
    choice = (1 - prevChoice)
  }
  return(choice)
}

```


```{r}
trials <- 120
n_participants <- 100 #unused

randomChoice <- (rep(NA,trials))
rate <- 0.5

#random
for (t in seq(trials)){
  randomChoice[t] <- RandomAgent_f(rate)
}

d1 <- tibble(trial = seq(trials), choice = randomChoice)
p1 <- ggplot(d1, aes(trial,choice)) + geom_line() + theme_classic()

p1
```

```{r}
#WSLS playing against Random

WSLSChoice <- rep(NA, trials)
WSLSChoice[1] <- RandomAgent_f(rate) #picks random on first trial

for (i in 2:trials){
  if (randomChoice[i-1] == WSLSChoice[i-1]){
    feedback = 1
  } else {feedback = 0}
  WSLSChoice[i] <- WSLSAgent_f(WSLSChoice[i-1], feedback)
}

#should make this into a function
df <- tibble(
  randomChoice,
  WSLSChoice,
  trials = seq(trials),
  feedback = as.numeric(randomChoice == WSLSChoice)) 
  
ggplot(df) + 
  theme_classic() + 
  geom_line(color = "red", aes(trials, randomChoice)) + 
  geom_line(color = "blue", aes(trials, WSLSChoice))
```
```{r}
df <-df %>% 
  mutate(cumulative_rateSelf= cumsum(feedback) / seq_along(feedback),
         cumulative_rateOther= cumsum(1-feedback) / seq_along(feedback) )

ggplot(df) + theme_classic() + geom_line(color="red", aes(trials, cumulative_rateSelf)) + geom_line(color="blue", aes(trials, cumulative_rateOther))
```
### ACTUAL competitor against Random & WSLS (Strategy Switcher)
```{r}
StratSwitcherChoice_f <- function(Other_Player, rate) {
  StratSwitcherChoice <- rep(NA, trials)
  StratSwitcherChoice[1] <- RandomAgent_f(rate) #picks random on first trial
  
  ResultMemory <- rep(NA, 5)
  WSLS_strategy <- TRUE
  feedback = NA
  
  StratSwitcherChoice[1] <- RandomAgent_f(rate)
  
  for (i in 2:trials) {
    #Starts off with checking feedback
    if (Other_Player[i - 1] == StratSwitcherChoice[i - 1]) {
      feedback = 1
    } else {
      feedback = 0
    }
    
    #add feedback to memory (5 tiles long)
    index <- ((i - 1) %% 5) + 1
    ResultMemory[index] <- feedback
    
    #switches choices every 5 trials if the last 5 trials have been bad
    if (i %% 5 == 0 && sum(ResultMemory, na.rm = TRUE) < 3) {
      #cat("Ahhh, I hate failure... switching; WSLS_strategy: ",WSLS_strategy,"trial number: ",i,"\n")
      if (WSLS_strategy == TRUE) {
        WSLS_strategy = FALSE
      } else {
        WSLS_strategy = TRUE
      }
    }
    
    #either plays WSLS or Random otherwise
    if (WSLS_strategy == TRUE) {
      StratSwitcherChoice[i] <- WSLSAgent_f(StratSwitcherChoice[i - 1], feedback)
    } else {
      StratSwitcherChoice[i] <- RandomAgent_f(rate)
    }
  }
  return (StratSwitcherChoice)
}

#play against both Random and WSLS
StratSwitcherChoice_against_Random <- StratSwitcherChoice_f(Other_Player = randomChoice, rate = 0.5)
StratSwitcherChoice_against_WSLS <- StratSwitcherChoice_f(Other_Player = WSLSChoice, rate = 0.5)
```

#Shitty plots
```{r}
#these should be made into functions
df1 <- tibble(
  randomChoice,
  StratSwitcherChoice_against_Random,
  trials = seq(trials),
  feedback = as.numeric(randomChoice == StratSwitcherChoice_against_Random)) #not using Other/Self
  
ggplot(df1) + 
  theme_classic() + 
  geom_line(color = "red", aes(trials, randomChoice)) + 
  geom_line(color = "blue", aes(trials, StratSwitcherChoice_against_Random))



df2 <- tibble(
  WSLSChoice,
  StratSwitcherChoice_against_WSLS,
  trials = seq(trials),
  feedback = as.numeric(WSLSChoice == StratSwitcherChoice_against_WSLS)) #not using Other/Self
  
ggplot(df2) + 
  theme_classic() + 
  geom_line(color = "red", aes(trials, WSLSChoice)) + 
  geom_line(color = "blue", aes(trials, StratSwitcherChoice_against_WSLS))
```

